---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: roboshop
  labels:
    project: roboshop
    component: frontend
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      project: roboshop
      component: frontend
      tier: frontend
  template:
    metadata:
      labels:
        project: roboshop
        component: frontend
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: joindevops/frontend:v1          # ← change this to your actual image if different
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 768Mi
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 6
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 45
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 5

# apiVersion: v1
# kind: Service
# metadata:
#   name: frontend
#   namespace: roboshop
#   labels:
#     project: roboshop
#     component: frontend
#     tier: frontend
# spec:
#   type: NodePort
#   selector:
#     project: roboshop
#     component: frontend
#     tier: frontend
#   ports:
#   - name: http
#     port: 80           # port inside cluster
#     targetPort: 8080   # container port
#     nodePort: 30080